name: opini_kopi
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.12.0
  flutter_dotenv: ^5.0.2
  image_picker: ^1.0.4
  fancy_shimmer_image: ^2.0.3
  intl: ^0.19.0
  fl_chart: ^1.2.0
  syncfusion_flutter_datepicker: ^24.1.41
  pdf: ^3.11.3
  printing: ^5.14.2
  excel: ^4.0.6
  path_provider: ^2.1.5
  esc_pos_utils_plus: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: "ic_launcher"
  image_path: "assets/app_icons/logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/app_icons/logo.png"
  web:
    generate: false

flutter:
  uses-material-design: true

  assets:
  - assets/images/
  - assets/app_icons/
  - .env
